export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SCRIPTS_REQUEST = 'SCRIPTS_REQUEST'
export const SCRIPTS_SUCCESS = 'SCRIPTS_SUCCESS'
export const SCRIPTS_FAILURE = 'SCRIPTS_FAILURE'

export const RUN_SCRIPT_REQUEST = 'RUN_SCRIPT_REQUEST'
export const RUN_SCRIPT_SUCCESS = 'RUN_SCRIPT_SUCCESS'
export const RUN_SCRIPT_FAILURE = 'RUN_SCRIPT_FAILURE'

export const EDIT_SCRIPT_REQUEST = 'EDIT_SCRIPT_REQUEST'
export const EDIT_SCRIPT_SUCCESS = 'EDIT_SCRIPT_SUCCESS'
export const EDIT_SCRIPT_FAILURE = 'EDIT_SCRIPT_FAILURE'

export const DELETE_SCRIPT_REQUEST = 'DELETE_SCRIPT_REQUEST'
export const DELETE_SCRIPT_SUCCESS = 'DELETE_SCRIPT_SUCCESS'
export const DELETE_SCRIPT_FAILURE = 'DELETE_SCRIPT_FAILURE'
