export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const GET_RSSHUB_ID_REQUEST = 'GET_RSSHUB_ID_REQUEST'
export const GET_RSSHUB_ID_SUCCESS = 'GET_RSSHUB_ID_SUCCESS'
export const GET_RSSHUB_ID_FAILURE = 'GET_RSSHUB_ID_FAILURE'

export const ADD_NEW_SCRIPT_REQEUST = 'ADD_NEW_SCRIPT_REQEUST'
export const ADD_NEW_SCRIPT_SUCCESS = 'ADD_NEW_SCRIPT_SUCCESS'
export const ADD_NEW_SCRIPT_FAILURE = 'ADD_NEW_SCRIPT_FAILURE'

export const GET_ALL_SCRIPT_REQUEST = 'GET_ALL_SCRIPT_REQUEST'
export const GET_ALL_SCRIPT_SUCCESS = 'GET_ALL_SCRIPT_SUCCESS'
export const GET_ALL_SCRIPT_FAILURE = 'GET_ALL_SCRIPT_FAILURE'

export const DELETE_SINGLE_SCRIPT_REQUEST = 'DELETE_SINGLE_SCRIPT_REQUEST'
export const DELETE_SINGLE_SCRIPT_SUCCESS = 'DELETE_SINGLE_SCRIPT_SUCCESS'
export const DELETE_SINGLE_SCRIPT_FAILURE = 'DELETE_SINGLE_SCRIPT_FAILURE'

export const UPDATE_ALL_SCRIPT_REQUEST = 'UPDATE_ALL_SCRIPT_REQUEST'
export const UPDATE_ALL_SCRIPT_SUCCESS = 'UPDATE_ALL_SCRIPT_SUCCESS'
export const UPDATE_ALL_SCRIPT_FAILURE = 'UPDATE_ALL_SCRIPT_FAILURE'

export const UPDATE_VISIBILITY = 'UPDATE_VISIBILITY'
