export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const GET_RSSHUB_ID_REQUEST = 'GET_RSSHUB_ID_REQUEST'
export const GET_RSSHUB_ID_SUCCESS = 'GET_RSSHUB_ID_SUCCESS'
export const GET_RSSHUB_ID_FAILURE = 'GET_RSSHUB_ID_FAILURE'

export const GET_RSSHUB_SCRIPT_REQUEST = 'GET_RSSHUB_SCRIPT_REQUEST'
export const GET_RSSHUB_SCRIPT_SUCCESS = 'GET_RSSHUB_SCRIPT_SUCCESS'
export const GET_RSSHUB_SCRIPT_FAILURE = 'GET_RSSHUB_SCRIPT_FAILURE'

export const GET_RSSHUB_UPDATE_REQUEST = 'GET_RSSHUB_UPDATE_REQUEST'
export const GET_RSSHUB_UPDATE_SUCCESS = 'GET_RSSHUB_UPDATE_SUCCESS'
export const GET_RSSHUB_UPDATE_FAILURE = 'GET_RSSHUB_UPDATE_FAILURE'
